apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: v2vvmwares.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: V2VVmware
    listKind: V2VVmwareList
    plural: v2vvmwares
    singular: v2vvmware
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            connection:
              type: string
            timeToLive:
              type: string
            vms:
              items:
                properties:
                  detail:
                    properties:
                      raw:
                        type: string
                    type: object
                  detailRequest:
                    type: boolean
                  name:
                    type: string
                required:
                - name
                type: object
              type: array
          type: object
        status:
          properties:
            phase:
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
